--- #YAML:1.0
name:               Mist-Menus
version:            1.0
abstract:           Create SDL Menus for Games and Apps
author:
    - Albert Graham <albert dot graham AT gmail  dot com>
license:            GPLv2+
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Text::Diff:  0
    SDL: 2.537
    SDL::TTF;
    SDL::Color;
    SDL::Rect;
    SDL::Event;
    SDL::Video;
    SDL::GFX::Primitives;
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
